name: Code Quality Check

on:
  pull_request:
  push:
    branches:
      - main
      - code-quality-task

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Node 18 to avoid engine errors

      - name: Install Dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint .  # Removed --ext flag
