name: Welcome New Contributors

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  welcome-contributor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Welcome Message
        run: |
          echo "Welcome to the project, ${{ github.actor }}!"
          # Alternatively, send message via Slack, Email, or Discord integration
